app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group

another_route:
    path: /profile
    defaults:
        _controller: AppBundle:Default:redirect
        route: redirect
        permanent: true
