# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#parameter_name: value

services:

    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_vname', 'plain_value', '%parameter_name%']
    app_mailer:
        class: AppBundle\Services\MailerService
        arguments: ['@service_container']